[package]
name = "info_distribution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
show-image = { version = "0.10.1", features = ["image"] }
image = "0.23.14"
ndarray = "0.15.4"
